<?php
/**
 * 作者: 距离
 * 日期: 2018/12/25
 * 时间: 20:23
 */

namespace Wechat\Menu;


class PersonalityMenu extends AbstractMenu
{
    public function createMenu($menuContent)
    {
        parent::createMenu($menuContent); // TODO: Change the autogenerated stub
    }

    public function queryMenu()
    {
        parent::queryMenu(); // TODO: Change the autogenerated stub
    }

    public function deleteMenu($params)
    {
        parent::deleteMenu($params); // TODO: Change the autogenerated stub
    }

}